# FastAPI routers grouped under app.api.*
from . import (
    admin_bookings,
    case_examples,
    chat,
    company_profile,
    company_reports,
    consultations,
    conversations,
    diagnosis,
    documents,
    experts,
    homework,
    memory,
    rag,
    report,
    reports,
)

__all__ = [
    "admin_bookings",
    "case_examples",
    "chat",
    "company_profile",
    "company_reports",
    "consultations",
    "conversations",
    "diagnosis",
    "documents",
    "experts",
    "homework",
    "memory",
    "rag",
    "report",
    "reports",
]
